name: CI
on:
  workflow_dispatch:
env:
  BASE_URL: ${{ secrets.BASE_URL }}
  MY_EMAIL: ${{ secrets.MY_EMAIL }}
  MY_PASS: ${{ secrets.MY_PASS }}
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
      # This workflow contains a single job called "build"
      build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        timeout-minutes: 30
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v3
          - name: Set up Python 3.13
            uses: actions/setup-python@v5
            with:
              python-version: "3.13"
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
#              pip install pipenv
              pip install python-dotenv
              pipenv install --system
              playwright install chromium

          - name: Run tests
            run: pytest