name: CI
on:
   push
env:
  BASE_URL: ${{ secrets.BASE_URL }}
  MY_EMAIL: ${{ secrets.MY_EMAIL }}
  MY_PASS: ${{ secrets.MY_PASS }}
jobs:
  build:
      runs-on: ubuntu-latest
#        timeout-minutes: 30
      steps:
          - uses: actions/checkout@v4
          - name: Set up Python 3.13
            uses: actions/setup-python@v5
            with:
                python-version: '3.13'
          - name: Install dependencies
            run:
              python -m pip install --upgrade pip
              pip install python-dotenv
#              pipenv install --system
              playwright install chromium

          - name: Run tests
            run: pytest