name: Playwright Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run tests
      run: pytest
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_PASS: ${{ secrets.MY_PASS }}
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
              #id: allure-report
      with:
        allure_results: reports
                #gh_pages: gh-pages
                #allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
      PERSONAL_TOKEN: ${{ secrets.PAT_TOKEN }}
      PUBLISH_BRANCH: gh-pages
      PUBLISH_DIR: allure-history