name: Playwright Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run tests
      run: pytest --alluredir=allure-results
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_PASS: ${{ secrets.MY_PASS }}


  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9
        with:
          PERSONAL_TOKEN: ${{ secrets.PAT_TOKEN }}
          permissions:
            id-token: write
            pages: write

#    - name: Get Allure history
#      uses: actions/checkout@v2
#      if: always()
#      continue-on-error: true
#      with:
#          ref: gh-pages
#          path: gh-pages
#
#    - name: 📦 Upload Allure Report
#      uses: simple-elf/allure-report-action@v1.7
#      if: always()
#      with:
#        gh_pages: gh-pages
#        allure_results: allure-results
#        allure_history: allure-history
#
#    - name: Deploy report to GitHub Pages
#      uses: peaceiris/actions-gh-pages@v3
#      with:
#        PERSONAL_TOKEN: ${{ secrets.PAT_TOKEN }}
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: allure-history