name: Playwright Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run tests
      run: pytest
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_PASS: ${{ secrets.MY_PASS }}